### ISSUE TITLE
Add title and description

### ISSUE THREAD

**Issue by hofmannsven** [wp-berlin/tech-website#11]
Add title tag and meta description to the home page.
Question: Do we need something like a tagline?

**Comment by alpipego** [comment]
Instead of using `wp_title()` as we're doing at the moment we should change that to

```
function theme_slug_setup() {
   add_theme_support( 'title-tag' );
}
add_action( 'after_setup_theme', 'theme_slug_setup' );
```

cf. https://make.wordpress.org/core/2014/10/29/title-tags-in-4-1/

I'd opt for https://wordpress.org/plugins/autodescription/ as an SEO Plugin. But I'm open to suggestions.

**Comment by alpipego** [comment]
I decided against an SEO plugin and instead opt for the following solution: Add metadata in comments at the beginning of the file, like

```
<!--
Title:			Content Security Policy, Proxy External Requests
Description: 		Introduction to Content Security Policy (CSP); the practical benefits, challenges, and limitations of CSP to guard against cross-site scripting attacks (XSS). And: How to proxy requests to external sources through your web server and when or when not to use this technique.
Robots: 		index, follow 
Date:			2018-05-08T19:00
Location:		Mozilla Berlin
Location-Search:	https://www.openstreetmap.org/node/4996803917
-->
```

(of course in the above example `Robots` is superfluous and should be left out)

The `Date` format should follow ISO_8601 without seconds, duration or a timezone identifier &ndash; and should be in local time.

`Location-Search` can be any link to a map provider or website. 

Any of these can be omitted (`Location-Search` without providing `Location` might not be reasonable).

The development will happen in https://github.com/alpipego/ghcp

The metadata parser will be extensible, so if we decide that we need more metadata, we'll be able to add it in.
