### ISSUE TITLE
Create /impressum

### ISSUE THREAD

**Issue by alpipego** [wp-berlin/tech-website#2]
Should be in German. 

@tichypress @svenbrier could you please take care of this? Just paste the text in this ticket.

**Comment by alpipego** [comment]
Since the code is now in the repo, the text can also go directly into [content/impressum.md](https://github.com/wp-berlin/tech-website/blob/master/content/impressum.md)

**Comment by svenbrier** [comment]
I have looked at the imprint on https://www.wpmeetup-hamburg.de/kontakt-impressum/ and think we could make our similar. What is your opinion?

It is open, who is responsible for the sub / domain. At https://wpmeetup-berlin.de/impressum/ are Bernhard's contact details.

I see three options for the subdomain:

- Bernhard
- Alex or Sven
- the WordPress Foundation

Again, what do you think?

**Comment by alpipego** [comment]
The first one is not an option. Without their explicit consent, I also don't think it could be the foundation.

**Comment by svenbrier** [comment]
Do you want to throw a coin or is there a volunteer?

**Comment by alpipego** [comment]
I still don't like the idea, but whatever. That also means that we cannot extend the write access to our content repositories.

Alexander Goller
Kurfürstenstr. 9
10785 Berlin
wp-berlin-tech@protonmail.com

**Comment by svenbrier** [comment]
We have a responsible person! ;) I'll have some time tomorrow in the bus while I'm on my way to Hanover and will try to finish the ticket during the trip.

**Comment by svenbrier** [comment]
Will we give a phone number in the imprint?
https://www.it-recht-kanzlei.de/handynummer-impressum.html

**Comment by svenbrier** [comment]
Question: Shouldn't the file be named imprint.md instead of impressum.md? Everything else is in English.

**Comment by alpipego** [comment]
Up until now at least Impressum has solely been a German requirement. Also, it is a German translation of the German word. I vote for keeping it at that.

> Will we give a phone number in the imprint?
Decisions not options; that said: If we add the organizer contacts to the Impressum as well, there will be enough means of communication.

**Comment by svenbrier** [comment]
Is it possible to name the Link 'Impressum' and the file 'imprint'?

**Comment by alpipego** [comment]
It is possible to name the link Impressum, but the path will be the filename (so `imprint` in this case).
