### ISSUE TITLE
GitHub repository meta

### ISSUE THREAD

**Issue by hofmannsven** [wp-berlin/tech-website#22]
Add topics, a short description, and the website URL for this repository. 
<img width="512" alt="repo-meta" src="https://user-images.githubusercontent.com/1214387/40400194-5e2ba146-5e41-11e8-9e83-06bfe37013e3.png">

This can only be done by admins and owners (see [repository permission levels for an organization](https://help.github.com/articles/repository-permission-levels-for-an-organization/)).

Proposal:
> Description: Official website of the WordPress Tech Meetup Berlin.
> URL: https://tech.wpmeetup-berlin.de/
> Topics: `wordpress-site`, `wordpress-theme`

**Comment by alpipego** [comment]
You now have admin rights on this repository ☺️
