### ISSUE TITLE
Allow Password for SQLite DB

### ISSUE THREAD

**Issue by alpipego** [wp-berlin/tech-website#29]
Right now, the config does not have an option to use an SQLite DB that is password-protected. 

We first need to check if the plugin allows for a password to be set: [Documentation](http://dogwood.skr.jp/wordpress/sqlite-integration/), [Original Plugin](https://wordpress.org/plugins/sqlite-integration/), if it does not we should PR it to the fork: https://github.com/alpipego/wp-sqlite-integration

**Comment by hofmannsven** [comment]
I do not think this is needed and I think we should go with the default setup. 
See #28 for further discussion.
