### ISSUE TITLE
Create /contribute page

### ISSUE THREAD

**Issue by alpipego** [wp-berlin/tech-website#3]
Create a contribute page (similar to https://github.com/wp-berlin/tech-meeting-minutes/blob/master/README.md).

What are the areas to contribute to?
How can people contribute?
&hellip;

**Comment by alpipego** [comment]
* Meeting Minutes
* Meetup organization
* Website Development

**Comment by alpipego** [comment]
More areas to contribute:

* Sponsoring
* Host a meetup, i.e. provide a location

**Comment by alpipego** [comment]
I suggest, that the potential topics (https://github.com/wp-berlin/tech-meeting-minutes/pull/4/files#diff-ab4c0222329fd2012284451baab062ff) will also go on this page.

**Comment by hofmannsven** [comment]
I'd also like to see the potential topics on this page.

How can potential hosts/sponsors/speakers contact us? Do we need to link to a contact form or provide a separate email address for this kind of contact request?

**Comment by alpipego** [comment]
@hofmannsven I have setup an email account, wp-berlin-tech@protonmail.com I'll relegate those email to the addresses in https://github.com/wp-berlin/planung/blob/master/organizer-contacts.md.

**Comment by alpipego** [comment]
Since the code is now in the repo, the text can also go directly into [content/contribute.md](https://github.com/wp-berlin/tech-website/blob/master/content/contribute.md)
