### ISSUE TITLE
Fatal error if there is no Meetup API key

### ISSUE THREAD

**Issue by hofmannsven** [wp-berlin/tech-website#42]
Without an [API key](https://secure.meetup.com/meetup_api/key/) I keep getting the following fatal error:

> Fatal error: Uncaught TypeError: Argument 1 passed to `WpBerlin\MeetupApi\Provider::__construct()` must be of the type `string`, `null` given, called in `/tech-website/web/plugins/meetup-api/meetup-api.php` on line 27 and defined in `/tech-website/web/plugins/meetup-api/src/Provider.php:19`

As hinted in the error message above, the parameter type `string` of `$apiKey` seems to cause this error:

```
public function __construct(string $apiKey, array $eventHosts)
```

**Comment by alpipego** [comment]
Hotfix in 1cb526abfc144300a2ad6d0e6e52f07eb4e5bb36
